version: "3.7"
services:
  postgres:
    build:
      context: ./database/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
  fastapi:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
      cd api &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./backend:/usr/src/app
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:root@postgres:5432/postgres"
  # react:
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:80
  #   environment:
  #     REACT_APP_BACKEND_URL: "10.202.105.49"
  #   depends_on:
  #     fastapi:
  #       condition: service_healthy
  #   command: nginx -g "daemon off;"
  #   healthcheck:
  #     test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
volumes:
  postgres-data: