version: "3.7"
services:
  fastapi:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    command: >
      bash -c "
      chmod +x /usr/src/app/set-env-with-secret.sh &&
      source /usr/src/app/set-env-with-secret.sh &&
      cd api &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./backend:/usr/src/app
    environment:
      STREAMING: "True"
      LOG_LEVEL: "DEBUG"
      MAX_RETRIES: "6"
      REQUEST_TIMEOUT: "100"
      LOG_GROUP : "/app/AMXChatbot"
      LOG_LOCAL_SETUP: "False"
  postgres:
    build:
      context: ./database/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data